version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    #driver: bridge

volumes:
  mongo-data:
    #driver: local
